import Head from "next/head";
import HabitTracker from "../../components/HabitTracker";
import HabitsProvider from "../../Providers/HabitsProvider";

function App() {
  return (
    <div className="flex h-screen bg-[#F5F5F5]">
      <Head>
        <title>HabitTracker | Headway</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/headway.svg" />
      </Head>
      <HabitsProvider>
        <HabitTracker />
      </HabitsProvider>
    </div>
  );
}

export default App;
