import Head from "next/head";
import { HabitsContext } from "../Providers/HabitsProvider";

import { startOfToday, sub } from "date-fns";

import React, { useContext, useEffect, useState } from "react";
import { colors, weekDays } from "../components/constants";
import HabitForm from "../components/HabitForm";
import { LogoutIcon } from "@heroicons/react/outline";
import { API_ENDPOINTS } from "../constants";
import { AnimatePresence } from "framer-motion";
import Image from "next/image";

const imgs = [
  "https://images.unsplash.com/photo-1579880251397-2c3ed174a774?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "https://images.unsplash.com/photo-1601141256817-c60897f2776a?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "https://images.unsplash.com/photo-1614152412509-7a5afc18c75b?q=80&w=3027&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "https://plus.unsplash.com/premium_photo-1661954372617-15780178eb2e?q=80&w=2920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
];

const Header = ({ setShowHabitForm }) => {
  return (
    <div className="flex gap-y-4 justify-between md:items-end">
      <p className="text-3xl font-bold text-[#2e2e2e]">Goals</p>
      <div className="flex justify-between md:justify-normal   items-end gap-3">
        <div className="flex gap-3">
          <button
            onClick={() => setShowHabitForm(true)}
            className={`flex justify-between items-center gap-2 font-medium   bg-[#0F85F2] px-4 py-2.5 rounded-full text-white disabled:cursor-not-allowed`}
          >
            <p>Add Goal</p>
          </button>
          <div>
            <button
              className="p-3 bg-white rounded-full text-gray-600 "
              onClick={() => {
                localStorage.removeItem("authToken");
                window.location.href = "/";
              }}
            >
              <LogoutIcon className=" w-6" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

function Goals() {
  const { habits, updateHabits } = useContext(HabitsContext);
  const [showHabitForm, setShowHabitForm] = useState(false);
  const today = startOfToday();
  const [error, setError] = useState(false);
  const [token, setToken] = useState(null);

  useEffect(() => {
    if (typeof window !== "undefined") {
      const token = window.localStorage.getItem("authToken");

      if (!token) {
        window.location.href = "/login";
      }

      setToken(token);
    }
  }, []);

  const dateWhichIsBeforeCurrDate = sub(today, {
    days: 5,
  });

  // use this if needed instead of today! 👆🏽

  const newHabit = {
    name: "",
    getDoneIn: "anytime",
    color: "",
    completedOnDates: [],
    createdDate: today,
    repeatHabitDays: weekDays,
  };

  const handleCreateHabit = async (habit) => {
    if (habit.name.trim().length === 0) {
      setError(true);
      return;
    } else {
      setError(false);

      if (habit.color === "") {
        const randomColor = colors[Math.floor(Math.random() * colors.length)];
        habit.color = randomColor;
      }

      if (habit.getDoneIn === "") {
        habit.getDoneIn = "anytime";
      }

      const res = await fetch(`${API_ENDPOINTS.BASE_URL}/newHabit`, {
        method: "POST",
        body: JSON.stringify({ habit: habit }),
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
      });
      const habitWithId = await res.json();

      const newHabits = [...(habits || []), habitWithId];

      updateHabits(newHabits);
      setShowHabitForm(false);
    }
  };

  return (
    <div className="flex h-screen bg-[#F5F5F5] relative overflow-hidden">
      <Head>
        <title>HabitTracker | Habstrack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/habstrack.svg" />
      </Head>
      <div className=" mx-auto w-full max-w-[90%]  md:max-w-[95%]  2xl:max-w-[70%] flex justify-between py-4 lg:py-8     lg:gap-8   ">
        <main className=" mx-auto w-full max-w-xl lg:max-w-[60%] ">
          <Header setShowHabitForm={setShowHabitForm} />
          <div className=" space-y-4   mt-8 gap-4 px-10 items-start scrollbar-hide h-[87vh]   overflow-auto ">
            {habits?.map((habit, idx) => {
              return (
                <div
                  key={idx}
                  className={` relative  flex bg-black  flex-col justify-between p-6 h-[300px] shadow-sm transition-shadow hover:shadow-lg hover:cursor-pointer group   rounded-2xl  w-full  `}
                >
                  {/* <p className="pb-1">💼</p> */}
                  <div className="z-10">
                    <p className=" font-semibold text-2xl   text-[#e1e1e1] capitalize pb-2  ">
                      {" "}
                      {habit.name}
                    </p>
                    <p className=" font-normal text-gray-400 pb-3  max-w-[30rem]   ">
                      Transform your physique by building muscle, increasing
                      strength, and achieving a powerful, sculpted look. Follow
                      a structured workout plan, ...
                    </p>
                  </div>

                  <div className="flex z-10  gap-4 items-center">
                    <div>
                      <p
                        className={`text-xs    capitalize    rounded-full    text-gray-400 `}
                      >
                        deadline date
                      </p>
                      <p
                        className={`text-sm py-1    capitalize  font-medium    rounded-full    text-gray-100 `}
                      >
                        25 / 05 / 24
                      </p>
                    </div>
                    <div>
                      <p
                        className={`text-xs    capitalize    rounded-full    text-gray-400 `}
                      >
                        time left
                      </p>
                      <p
                        className={`text-sm py-1    capitalize font-medium    rounded-full    text-gray-100 `}
                      >
                        25 Days
                      </p>
                    </div>
                  </div>
                  <div className=" absolute  right-0 top-0 h-full  rounded-lg  overflow-hidden  gap-2">
                    <div className="w-[400px] absolute z-[8] h-[400px] bg-gradient-to-r from-black "></div>
                    <Image
                      src={imgs[idx]}
                      width="400"
                      height="400"
                      className=" w-full rounded-lg text-center  "
                      alt="headay's habit tracker img"
                    />
                  </div>
                </div>
              );
            })}
          </div>
        </main>
        <AnimatePresence>
          {showHabitForm ? (
            <HabitForm
              formTitle="Add New Habit"
              habit={newHabit}
              setShowHabitForm={setShowHabitForm}
              handleSubmit={handleCreateHabit}
              error={error}
            />
          ) : null}
        </AnimatePresence>
      </div>
    </div>
  );
}

export default Goals;
