import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import headway from "../public/headway.png";
import HabitScheduler from "../public/Schedulers.svg";
import HabitStats from "../public/Stats.svg";
import { Check } from "react-feather";

export default function Home() {
  const CirclCheckBox = () => {
    return (
      <div className="bg-white rounded-full w-10 flex justify-center shadow-md items-center h-10 ">
        <Check className=" stroke-green-500 rounded-2xl stroke-3 " />
      </div>
    );
  };

  const InfoCard = ({ title, description }) => {
    return (
      <div className="flex gap-6">
        <CirclCheckBox />
        <p className=" flex-1 max-w-md  md:text-xl font-medium text-[#6D7280] ">
          <strong className="text-[#303850]"> {title}</strong> : {description}
        </p>
      </div>
    );
  };

  return (
    <div>
      <Head>
        <title>Habstrack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/habstrack.svg" />
      </Head>
      <main
        className="flex md:items-start md:p-40 justify-center md:h-[100vh]    bg-gradient-to-b from-transparent bg-opacity-[0.2] to-[#0c39aa0c]
via-white  via-opacity-5 relative  "
      >
        <main className=" z-50 flex flex-col text-center items-center max-w-md lg:max-w-xl xl:max-w-3xl px-6 gap-y-6   my-10 md:my-0 mx-auto ">
          <div className="">
            <h1 className=" font-bold mb-6 text-3xl sm:text-4xl lg:text-5xl xl:text-7xl text-center text-[#212121]  ">
              Build Better Habits with
              <em className="underline decoration-blue-400  inline mx-2 sm:mx-3 xl:mx-5 ">
                Habstrack
              </em>
              Today!
            </h1>
            <blockquote className=" font-medium tracking-wide  	 sm:text-lg lg:text-xl  text-slate-500 ">
              Take the First Step Towards a Better Life, Track Your Habits,
              Achieve Your Goals, and Build a Happier, Healthier You.
            </blockquote>
          </div>

          <Link
            className=" font-medium  bg-gradient-to-bl  from-[#0FC9F2] to-[#0F85F2] px-8 lg:px-11 lg:py-4 py-3 xl:px-14   lg:shadow-2xl lg:shadow-blue-400  rounded-lg text-lg text-white"
            href="/login"
          >
            Start tracking!
          </Link>
        </main>
        <div className=" absolute w-[400px]  h-[400px] left-[-169.45px] top-[-172.22px] bg-[#0C38AA] opacity-[0.2] filter blur-[149.306px]  "></div>
        <div className=" hidden lg:block  absolute w-[400px]  h-[400px] left-[800px] 2xl:left-[1100px] xl:top-[100px] bg-[#0C38AA] opacity-[0.2] filter blur-[149.306px]   "></div>
      </main>

      <section className="md:h-[50vh] bg-[#F0F1F5] ">
        <Image
          src={headway}
          width="1184"
          className=" md:absolute md:top-[500px] md:left-1/2  md:transform md:-translate-x-1/2 top-[600px] border-[1rem] rounded-lg border-white  "
          alt="headay's habit tracker img"
        />
      </section>

      <section className=" h-[100vh] bg-[#F0F1F5]   ">
        <div className="  py-20 grid md:grid-cols-2 max-w-xs md:max-w-6xl h-[100vh] mx-auto">
          <div className=" space-y-6 md:space-y-12">
            <h2 className="font-bold text-2xl  md:text-4xl  text-[#212121] ">
              Track Your Progress <br /> with Ease
            </h2>
            <InfoCard
              title="Know your streaks"
              description="Keep
          track of your current and best streaks to stay motivated and achieve
          your goals."
            />
            <InfoCard
              title="Habits Score"
              description="Get a clear picture of how far you've come by viewing your completion percentage for each habit."
            />
            <InfoCard
              title="Times Completed"
              description="View a quick summary of times completed for the selected habit, including this week, this month, and this year."
            />
          </div>
          <Image
            src={HabitStats}
            className=" relative top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2  "
            alt="headay's habit tracker img"
          />
        </div>
      </section>

      <section className=" h-[100vh]    ">
        <div className="  py-20 grid md:grid-cols-2  max-w-xs md:max-w-6xl h-[100vh] mx-auto">
          <Image
            width={500}
            src={HabitScheduler}
            className=" relative top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2  "
            alt="headay's habit tracker img"
          />
          <div className="space-y-6 md:space-y-12">
            <h2 className="font-bold text-2xl  md:text-4xl  text-[#212121] ">
              Habit Tracking on <br /> Your Terms
            </h2>
            <InfoCard
              title="Flexible habit scheduling"
              description="Choose which days of the week you want to complete a habit, and track your progress with ease."
            />
            <InfoCard
              title="Color-coded habits"
              description="Assign a unique color to each habit to keep them organized and visually appealing."
            />
            <InfoCard
              title="Choose your habit time"
              description="Set a schedule that works for you, whether that's morning, afternoon, or evening."
            />
          </div>
        </div>
      </section>
      <section className="  bg-[#0D0D0D] py-32    ">
        <div className="max-w-4xl mx-auto flex flex-col  gap-14 items-center">
          <h2 className="font-bold text-2xl md:text-5xl text-center  text-white ">
            Do the hard work especially <br /> when you dont feel like it!
          </h2>
          <button className=" font-medium  bg-gradient-to-bl from-[#0FC9F2] to-[#0F85F2] px-14 py-4  rounded-lg text-lg text-white">
            <Link href="/habits">Build Habits Right Now!</Link>
          </button>
        </div>
      </section>
    </div>
  );
}
