import Link from "next/link";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Headway</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/headway.svg" />
      </Head>
      <main
        className="flex items-center justify-center  h-[100vh]  bg-gradient-to-b from-transparent bg-opacity-[0.2] to-[#0c39aa0c]
via-white  via-opacity-5  "
      >
        <main className=" z-50 flex flex-col text-center items-center  gap-4 max-w-3xl space-y-8  my-10 mx-auto ">
          <h1 className=" font-bold text-7xl text-center text-[#212121]  ">
            Build Better Habits with
            <p className="underline decoration-blue-400  inline px-5 ">
              Headway
            </p>
            Today!
          </h1>
          <p className=" font-medium text-xl text-slate-500 ">
            Take the First Step Towards a Better Life with Headway: Track Your
            Habits, Achieve Your Goals, and Build a Happier, Healthier You.
          </p>
          <Link
            className=" font-medium  bg-gradient-to-bl from-[#0FC9F2] to-[#0F85F2] px-14 py-4 shadow-2xl shadow-blue-400  rounded-lg text-lg text-white"
            href="/app"
          >
            Start tracking!
          </Link>
        </main>

        <div className=" absolute w-[400px]  h-[400px] left-[830px] top-[100px] bg-[#0C38AA] opacity-[0.2] filter blur-[149.306px]  "></div>
        <div className=" absolute w-[400px]  h-[400px] left-[-169.45px] top-[-172.22px] bg-[#0C38AA] opacity-[0.2] filter blur-[149.306px]  "></div>
      </main>
    </div>
  );
}
