import Head from "next/head";
import { AnimatePresence, motion } from "framer-motion";

const transitionMain = {
  bounce: 0,
  type: "spring",
};

export default function Home() {
  return (
    <div>
      <Head>
        <title>Habstrack Waitlist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/headway.svg" />
      </Head>
      <main
        className="flex md:items-center justify-center md:h-[100vh]    bg-gradient-to-b from-transparent bg-opacity-[0.2] to-[#0c39aa0c]
via-white  via-opacity-5 relative  "
      >
        <main className=" z-50 flex flex-col text-center items-center max-w-md lg:max-w-xl xl:max-w-3xl px-6 space-y-6 lg:space-y-10 xl:space-y-16  my-10 mx-auto ">
          <AnimatePresence>
            <div className="space-y-4 lg:space-y-6 xl:space-y-8">
              <motion.h1
                initial={{
                  y: 100,
                  opacity: 0,
                }}
                animate={{
                  y: 0,
                  opacity: 1,
                }}
                transition={{
                  duration: 1.2,
                  ...transitionMain,
                }}
                className=" font-bold text-3xl sm:text-4xl lg:text-6xl  text-center text-[#212121]  "
              >
                Your ultimate
                <br />
                <span className="underline decoration-blue-400  inline mx-2 sm:mx-3 xl:mx-5 ">
                  Self Improvement {""}
                </span>
                app{" "}
              </motion.h1>
              <motion.blockquote
                initial={{
                  y: 50,
                  opacity: 0,
                }}
                animate={{
                  opacity: 1,
                  y: 0,
                }}
                transition={{
                  delay: 0.4,
                  duration: 1.1,
                  ...transitionMain,
                }}
                className="  tracking-wide  	 sm:text-lg lg:text-xl  text-gray-600 "
              >
                Your habits, meditations, workouts, and journals in one place.
                Join a supportive community and become the best version of
                yourself.
              </motion.blockquote>
            </div>

            <motion.button
              initial={{
                y: 50,
                opacity: 0,
              }}
              animate={{
                y: 0,
                opacity: 1,

                transition: {
                  delay: 0.6,
                  type: "spring",
                  bounce: 0,
                  duration: 1.2,
                },
              }}
              whileHover={{
                scale: 1.1,
                transition: {
                  type: "spring",
                  bounce: 0,
                  duration: 0.4,
                },
              }}
              whileTap={{
                scale: 1,
                transition: {
                  type: "spring",
                  bounce: 0,
                  duration: 0.4,
                },
              }}
              className=" font-medium   bg-[#212121] text-white px-8 lg:px-11 lg:py-4 py-3 xl:px-14     rounded-full text-lg "
            >
              Stay Updated
            </motion.button>
          </AnimatePresence>
        </main>
        <div className=" absolute w-[400px]  h-[400px] left-[-169.45px] top-[-172.22px] bg-[#0C38AA] opacity-[0.2] filter blur-[149.306px]  "></div>
        <div className=" hidden lg:block  absolute w-[400px]  h-[400px] left-[800px] 2xl:left-[1100px] xl:top-[100px] bg-[#0C38AA] opacity-[0.2] filter blur-[149.306px]   "></div>
      </main>
    </div>
  );
}
