import Head from "next/head";
import { AnimatePresence, motion } from "framer-motion";
import { useState } from "react";
import { API_ENDPOINTS } from "../constants";

const transitionMain = {
  bounce: 0,
  type: "spring",
};

export default function Home() {
  const [email, setEmail] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [buttonText, setButtonText] = useState("Stay Updated");

  const emailPattern = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
  const isValid = emailPattern.test(email);

  const handleSubmit = async () => {
    if (!isValid) {
      setButtonText("Incorrect Email!");

      setTimeout(() => {
        setButtonText("Stay Updated");
      }, 3000);
      return;
    }

    setIsLoading(true);
    setButtonText("Adding...");

    const res = await fetch(`${API_ENDPOINTS.BASE_URL}/waitlist`, {
      method: "POST",
      body: JSON.stringify({ email }),
      headers: {
        "Content-Type": "application/json",
      },
    });

    const data = await res.json();
    if (data.message) {
      setTimeout(() => {
        setIsLoading(false);
        setButtonText(data.message);
      }, 2000);
    }
  };

  return (
    <div>
      <Head>
        <title>Habstrack Waitlist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/headway.svg" />
      </Head>
      <main
        className="flex  md:items-center justify-center h-screen md:h-[100vh]    bg-gradient-to-b from-transparent bg-opacity-[0.2] to-[#0c39aa0c]
via-white  via-opacity-5 relative  "
      >
        <main className=" z-50 flex flex-col text-center items-center max-w-md lg:max-w-xl xl:max-w-3xl px-6 space-y-6 lg:space-y-10 xl:space-y-16 mt-56 md:mt-0  my-10 mx-auto ">
          <AnimatePresence>
            <div className="space-y-4 lg:space-y-6 xl:space-y-8">
              <motion.h1
                initial={{
                  y: 100,
                  opacity: 0,
                }}
                animate={{
                  y: 0,
                  opacity: 1,
                }}
                transition={{
                  duration: 1.2,
                  ...transitionMain,
                }}
                className=" font-bold text-3xl sm:text-4xl lg:text-6xl  text-center text-[#212121]  "
              >
                Your ultimate
                <br />
                <span className="underline decoration-blue-400  inline mx-2 sm:mx-3 xl:mx-5 ">
                  Self Improvement {""}
                </span>
                app{" "}
              </motion.h1>
              <motion.blockquote
                initial={{
                  y: 50,
                  opacity: 0,
                }}
                animate={{
                  opacity: 1,
                  y: 0,
                }}
                transition={{
                  delay: 0.4,
                  duration: 1.1,
                  ...transitionMain,
                }}
                className="  tracking-wide  	 sm:text-lg lg:text-xl  text-gray-600 "
              >
                Your habits, meditations, workouts, and journals in one place.
                Join a supportive community and become the best version of
                yourself.
              </motion.blockquote>
            </div>

            <div className="md:flex justify-center items-center gap-2">
              <motion.input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                initial={{
                  y: 50,
                  opacity: 0,
                }}
                animate={{
                  y: 0,
                  opacity: 1,

                  transition: {
                    delay: 0.6,
                    type: "spring",
                    bounce: 0,
                    duration: 1.2,
                  },
                }}
                placeholder="Email"
                className=" font-medium  text-gray-800 bg-white  px-8 min-w-full lg:py-4 py-3  border focus:outline-gray-400     rounded-full md:text-lg "
              />

              <motion.button
                disabled={isLoading || email === ""}
                onClick={() => handleSubmit()}
                initial={{
                  y: 50,
                  opacity: 0,
                }}
                animate={{
                  y: 0,
                  opacity: 1,

                  transition: {
                    delay: 0.6,
                    type: "spring",
                    bounce: 0,
                    duration: 1.2,
                  },
                }}
                whileHover={{
                  scale: 1.1,
                  transition: {
                    type: "spring",
                    bounce: 0,
                    duration: 0.2,
                  },
                }}
                whileTap={{
                  scale: 1,
                  transition: {
                    type: "spring",
                    bounce: 0,
                    duration: 0.4,
                  },
                }}
                className=" font-medium disabled:bg-opacity-80 disabled:cursor-not-allowed min-w-full md:min-w-fit mt-3 md:mt-0 focus:outline-gray-400   bg-[#212121] text-white px-4 md:px-8  lg:py-4 py-3     rounded-full md:text-lg "
              >
                {buttonText}
              </motion.button>
            </div>
          </AnimatePresence>
        </main>
        <div className=" absolute w-[400px]  h-[400px] left-[-169.45px] top-[-172.22px] bg-[#0C38AA] opacity-[0.2] filter blur-[149.306px]  "></div>
        <div className=" hidden lg:block  absolute w-[400px]  h-[400px] left-[800px] 2xl:left-[1100px] xl:top-[100px] bg-[#0C38AA] opacity-[0.2] filter blur-[149.306px]   "></div>
      </main>
    </div>
  );
}
